[package]
name = "vault"
version = "0.0.1"
authors = ["Liber Wang <liberwang1013@gmail.com>"]
edition = "2018"

[lib]
name = "vault"
path = "src/lib.rs"

[dev-dependencies]
log = "^0.4"
env_logger = "0.7"
tokio = "0.2.0-alpha.6"

[dependencies]
url = "^2.1"
http = "^0.2"
bytes = "0.5"

reqwest = {version = "0.10", features = ["json"]}
futures-util = { version = "^0.3.0", default-features = false }
futures-core = { version = "^0.3.0", default-features = false }

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
