[package]
name = "vault"
version = "0.0.1"
authors = ["Liber Wang <liberwang1013@gmail.com>"]
edition = "2018"

[lib]
name = "vault"
path = "src/lib.rs"

[workspace]
members = ["example"]

[dev-dependencies]
env_logger = "0.6.1"

[dependencies]
log = "0.4"
reqwest = "0.9.15"
http = "0.1.17"
serde = {version = "1.0.90", features = ["derive"]}
serde_json = "1.0.39"

error-chain = "0.12.1"